apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clickhouse-deployment.yaml
  - clusterlogging-hub.yaml
  - kafka-cluster.yaml
  - kafka-topics.yaml
  - langfuse-postgres-cluster.yaml
  - langfuse-route.yaml
  - lokistack-hub.yaml
  - pgvector-cluster.yaml
  - redis-deployment.yaml
