apiVersion: v1
kind: Secret
metadata:
  name: aap-edge-credentials
  namespace: aap
type: Opaque
stringData:
  EDGE_API_URL: "https://api.REPLACE_ME_EDGE_CLUSTER:6443"
  EDGE_API_TOKEN: "REPLACE_WITH_EDGE_CLUSTER_TOKEN"
