apiVersion: v1
kind: Secret
metadata:
  name: aap-edge-credentials
  namespace: aap
type: Opaque
stringData:
  EDGE_API_URL: "REPLACE_WITH_EDGE_API_URL"
  EDGE_API_TOKEN: "REPLACE_WITH_EDGE_CLUSTER_TOKEN"
