apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aap-platform.yaml
  - automation-controller.yaml
  - eda-controller.yaml
  - managed-cluster.yaml
  - multiclusterhub.yaml
