apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aap-platform.yaml
  - aap-admin-secret.yaml
  - aap-bootstrap-job.yaml
  - managed-cluster.yaml
  - multiclusterhub.yaml
