apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/agent-mcp
configMapGenerator:
  - name: dark-noc-agent-code
    files:
      - runtime-code/agent.py
      - runtime-code/state.py
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Deployment
      name: mcp-openshift
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/msugur/auto-darknoc:mcp-openshift-gitsha
  - target:
      kind: Deployment
      name: mcp-lokistack
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/msugur/auto-darknoc:mcp-lokistack-gitsha
  - target:
      kind: Deployment
      name: mcp-kafka
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/msugur/auto-darknoc:mcp-kafka-gitsha
  - target:
      kind: Deployment
      name: mcp-aap
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/msugur/auto-darknoc:mcp-aap-gitsha
  - target:
      kind: Deployment
      name: mcp-slack
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/msugur/auto-darknoc:mcp-slack-gitsha
  - target:
      kind: Deployment
      name: mcp-servicenow
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/msugur/auto-darknoc:mcp-servicenow-gitsha
  - target:
      kind: Deployment
      name: dark-noc-agent
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/msugur/auto-darknoc:agent-gitsha
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: dark-noc-agent-code
            configMap:
              name: dark-noc-agent-code
              defaultMode: 420
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: dark-noc-agent-code
            mountPath: /app/agent.py
            subPath: agent.py
          - name: dark-noc-agent-code
            mountPath: /app/state.py
            subPath: state.py
