apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-pipeline-hub
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: auto-darknoc-prod
  source:
    repoURL: https://github.com/msugur/auto-darknoc.git
    targetRevision: main
    path: gitops/prod/stacks/hub/data-pipeline
  destination:
    name: in-cluster
    namespace: dark-noc-kafka
  ignoreDifferences:
    - group: build.openshift.io
      kind: BuildConfig
      name: pgvector-postgres
      namespace: dark-noc-rag
      jsonPointers:
        - /spec/failedBuildsHistoryLimit
        - /spec/successfulBuildsHistoryLimit
        - /spec/nodeSelector
        - /spec/postCommit
        - /spec/resources
        - /spec/runPolicy
        - /spec/strategy/dockerStrategy
    - group: postgresql.cnpg.io
      kind: Cluster
      name: pgvector-postgres
      namespace: dark-noc-rag
      jsonPointers:
        - /spec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
