apiVersion: v1
kind: Secret
metadata:
  name: platform-credentials
  namespace: dark-noc-gitops
type: Opaque
stringData:
  HUB_CONSOLE_URL: "REPLACE_WITH_HUB_CONSOLE_URL"
  HUB_API_URL: "REPLACE_WITH_HUB_API_URL"
  EDGE_CONSOLE_URL: "REPLACE_WITH_EDGE_CONSOLE_URL"
  EDGE_API_URL: "REPLACE_WITH_EDGE_API_URL"
  HUB_CPU_MACHINESET: "REPLACE_WITH_HUB_CPU_MACHINESET"
  HUB_CPU_REPLICAS: "1"

  DASHBOARD_URL: "REPLACE_WITH_DASHBOARD_ROUTE"
  CHATBOT_URL: "REPLACE_WITH_CHATBOT_ROUTE"
  GRAFANA_URL: "REPLACE_WITH_GRAFANA_ROUTE"
  LANGFUSE_URL: "REPLACE_WITH_LANGFUSE_ROUTE"

  AAP_URL: "REPLACE_WITH_AAP_ROUTE"
  AAP_USERNAME: "admin"
  AAP_PASSWORD: "redhat"
  AAP_LIGHTSPEED_TEMPLATE: "lightspeed-generate-and-run"

  SERVICENOW_URL: "REPLACE_WITH_SERVICENOW_URL"
  SERVICENOW_USERNAME: "REPLACE_WITH_SERVICENOW_USERNAME"
  SERVICENOW_PASSWORD: "REPLACE_WITH_SERVICENOW_PASSWORD"

  SLACK_WORKSPACE_URL: "REPLACE_WITH_SLACK_WORKSPACE_URL"
  SLACK_NOC_CHANNEL: "REPLACE_WITH_SLACK_CHANNEL"
  SLACK_BOT_TOKEN: "REPLACE_WITH_XOXB_TOKEN"
