apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auto-darknoc-prod
  namespace: openshift-gitops
spec:
  description: Auto Dark NOC production project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    - namespace: '*'
      name: edge-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
